# Generated by Django 4.1 on 2025-08-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabiit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, default='', null=True)),
                ('prompt', models.TextField(default='', null=True)),
                ('content', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generaltutorlesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_tutor.generaltutorlesson')),
            ],
        ),
    ]
