# Generated by Django 4.1 on 2025-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabiit',
            name='highlighted_text',
            field=models.TextField(default='', null=True),
        ),
    ]
