# Generated by Django 4.1 on 2025-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rabiit_highlighted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabiit',
            name='selected_image_url',
            field=models.TextField(default='', null=True),
        ),
    ]
