# Generated by Django 4.1 on 2025-08-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorlesson',
            name='bitesize',
        ),
        migrations.RemoveField(
            model_name='generaltutorlesson',
            name='conversation',
        ),
    ]
