# Generated by Django 4.1 on 2025-08-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_source_source_type'),
        ('general_tutor', '0003_remove_generaltutorlesson_bitesize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorlesson',
            name='query',
        ),
        migrations.AddField(
            model_name='generaltutorlesson',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
        migrations.AlterField(
            model_name='generaltutorlesson',
            name='lessontitle',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
