# Generated by Django 4.1 on 2025-08-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_tutor', '0004_remove_generaltutorlesson_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorlesson',
            name='completed',
        ),
        migrations.CreateModel(
            name='GeneralTutorSpaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_track', models.JSONField(default=dict, null=True)),
                ('saved', models.BooleanField(default=False, null=True)),
                ('editable', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_tutor.generaltutorspace')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('space', 'user')},
            },
        ),
    ]
