# Generated by Django 4.1 on 2025-08-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0005_remove_generaltutorlesson_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorlesson',
            name='space',
        ),
        migrations.AddField(
            model_name='generaltutorlesson',
            name='space_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_tutor.generaltutorspacesubscription'),
        ),
    ]
