# Generated by Django 4.1 on 2025-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0006_remove_generaltutorlesson_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltutorspace',
            name='is_shareable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
