# Generated by Django 4.1 on 2025-08-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0007_generaltutorspace_is_shareable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaltutorspace',
            old_name='is_shareable',
            new_name='editable',
        ),
        migrations.RenameField(
            model_name='generaltutorspacesubscription',
            old_name='editable',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='generaltutorspacesubscription',
            name='saved',
        ),
    ]
