# Generated by Django 4.1 on 2025-08-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0008_rename_is_shareable_generaltutorspace_editable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaltutorspacesubscription',
            old_name='owner',
            new_name='is_owner',
        ),
    ]
