# Generated by Django 4.1 on 2025-08-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0009_rename_owner_generaltutorspacesubscription_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorspacesubscription',
            name='progress_track',
        ),
    ]
