# Generated by Django 4.1 on 2025-08-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0010_remove_generaltutorspacesubscription_progress_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltutorlesson',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
