# Generated by Django 4.1 on 2025-08-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0011_generaltutorlesson_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltutorspace',
            name='editable',
        ),
    ]
