# Generated by Django 4.1 on 2025-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tutor', '0012_remove_generaltutorspace_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltutorspace',
            name='is_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
