# Generated by Django 4.1 on 2025-08-26 10:14

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, default=0, null=True)),
                ('content', models.TextField(default='', null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Vector embeddings of the chunk', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('s3_key', models.CharField(blank=True, default='', max_length=1000)),
                ('video_id', models.CharField(blank=True, default='', max_length=25)),
                ('presiged_post', models.JSONField(blank=True, default=dict, null=True)),
                ('full_content', models.TextField(blank=True, default='')),
                ('vtt_transcript', models.TextField(blank=True, default='', null=True)),
                ('source_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('WEB', 'WEB'), ('WEBDOC', 'WEBDOC'), ('TEXT', 'TEXT'), ('Youtube', 'Youtube'), ('IMG', 'IMG')], max_length=10, null=True)),
                ('is_question_sheet', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_uploaded', models.BooleanField(default=False, null=True)),
                ('pipeline_start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('pipeline_started', models.BooleanField(default=False, null=True)),
                ('pipeline_completed', models.BooleanField(default=False, null=True)),
                ('pipeline_failed', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceLessonActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_key', models.CharField(db_index=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_activation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.sourceactivation')),
            ],
        ),
        migrations.AddField(
            model_name='sourceactivation',
            name='lesson_activations',
            field=models.ManyToManyField(related_name='source_lesson_activation', to='sources.sourcelessonactivation'),
        ),
        migrations.AddField(
            model_name='sourceactivation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
    ]
