# Generated by Django 4.1 on 2025-08-26 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_tutor', '0002_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceactivation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_tutor.generaltutorspace'),
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunk',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunk_source', to='sources.source'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['source', 'number'], name='sources_chu_source__c3438a_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='question_embedding_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('source', 'number')},
        ),
    ]
