# Generated by Django 4.1 on 2025-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('WEB', 'WEB'), ('WEBDOC', 'WEBDOC'), ('TEXT', 'TEXT'), ('IMG', 'IMG')], max_length=10, null=True),
        ),
    ]
