# Generated by Django 4.1 on 2025-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_source_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='vtt_transcript',
        ),
    ]
