# Generated by Django 4.1 on 2025-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_remove_source_vtt_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='concept_outline',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
